# Generated by Django 4.2.3 on 2023-07-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchpapers',
            name='pssn',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='researchpapers',
            name='tdept',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='researchpapers',
            name='tid',
            field=models.CharField(max_length=10),
        ),
    ]
