# Generated by Django 4.2.3 on 2023-07-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_alter_researchpapers_pssn_alter_researchpapers_tdept_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchpapers',
            name='plink',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='researchpapers',
            name='ptitle',
            field=models.CharField(max_length=100),
        ),
    ]
