# Generated by Django 4.2.3 on 2023-07-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_alter_researchpapers_plink_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailid', models.CharField(max_length=40)),
                ('issue', models.CharField(max_length=400)),
            ],
        ),
    ]
