# Generated by Django 4.2.3 on 2023-07-18 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0004_report'),
    ]

    operations = [
        migrations.DeleteModel(
            name='report',
        ),
    ]
